name: Deploy Next.js App

on:
  push:
    branches:
      - main


env:
  REGISTRY: ghcr.io
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TEAM }}

  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build with Turbo
        run: |
          npx turbo build --dry && npx turbo build
          
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login Registry
        run: |
          echo ${{ secrets.PAT }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ github.actor }}/turbo-with-docker-api:latest
          cache-from: type=registry,ref=${{ github.actor }}/turbo-with-docker-api:latest
          cache-to: type=inline
          context: .
          file: apps/api/Dockerfile
          build-args: TURBO_TEAM,TURBO_TOKEN
            
          
