name: Deploy Next.js App

on:
  push:
    branches:
      - main


env:
  REGISTRY: ghcr.io
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TEAM }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login Registry
        run: |
          echo ${{ secrets.PAT }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
          
      - name: Build and push for api
        id: docker_build_api
        uses: docker/build-push-action@v6
        env: 
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ github.actor }}/turbo-with-docker-api:latest
          FILE: apps/api/Dockerfile
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}
          cache-to: type=inline
          context: .
          file: ${{ env.FILE }}
          build-args: TURBO_TEAM,TURBO_TOKEN
      - run: |
          echo "Docker Image ID: ${{ steps.docker_build_api.outputs.imageid }}"
          echo "Docker Image digest: ${{ steps.docker_build_api.outputs.digest }}"
          echo "Docker Image metadata: ${{ steps.docker_build_api.outputs.metadata }}"
          
      - name: Build and push for web
        id: docker_build_web
        uses: docker/build-push-action@v6
        env: 
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ github.actor }}/turbo-with-docker-web:latest
          FILE: apps/web/Dockerfile
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}
          cache-to: type=inline
          context: .
          file: ${{ env.FILE }}
          build-args: TURBO_TEAM,TURBO_TOKEN
      - run: |
          echo "Docker Image ID: ${{ steps.docker_build_web.outputs.imageid }}"
          echo "Docker Image digest: ${{ steps.docker_build_web.outputs.digest }}"
          echo "Docker Image metadata: ${{ steps.docker_build_web.outputs.metadata }}"
            
          
